version: 2.1

executors:
  cypress-executor:
    docker:
<<<<<<< HEAD
      - image: cypress/included:14.0.3  # Escolha a versão do Cypress desejada
    working_directory: ~/word-counter-page/cypress
=======
      - image: cypress/included:14.0.3
    working_directory: ~/project/cypress
>>>>>>> origin/circleci-project-setup

jobs:
  cypress-run:
    executor: cypress-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run Cypress Tests
          command: npx cypress run
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots
      - store_artifacts:
          path: cypress/videos
          destination: videos
      - store_test_results:
          path: cypress/results

workflows:
  version: 2
  cypress-tests:
    jobs:
      - cypress-run
